# Generated by Django 3.2.4 on 2021-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD')], default='BDT', max_length=3)),
                ('source', models.CharField(choices=[('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('Bank', 'Bank Account')], default='Bank', max_length=6)),
            ],
        ),
    ]
