# Generated by Django 3.2.4 on 2021-06-24 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20210623_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(blank=True, choices=[('Transportation', 'Transport Bill'), ('Rent', 'Rent'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Entertainment', 'Entertainment')], default='Transportation', max_length=14),
        ),
        migrations.AddField(
            model_name='expense',
            name='utilities',
            field=models.CharField(blank=True, choices=[('Electric', 'Electric Bill'), ('Water', 'Water Bill'), ('Gas', 'Gas Bill'), ('Oil', 'Oil Purchase'), ('Internet', 'Internet Bill'), ('CellPhone', 'CellPhone Bill')], default='CellPhone', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.wallet'),
        ),
        migrations.AlterField(
            model_name='lendmoney',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='liability',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
