# Generated by Django 3.2.4 on 2021-06-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20210624_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='prev_balance',
        ),
    ]
