# Generated by Django 3.2.4 on 2021-06-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20210624_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
