# Generated by Django 3.2.4 on 2021-06-24 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_expense_expense_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='current_balance',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='prev_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.expense'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='prev_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
