# Generated by Django 3.2.4 on 2021-06-24 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0012_auto_20210624_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='spender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
