# Generated by Django 3.2.4 on 2021-06-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0014_auto_20210625_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
