# Generated by Django 3.2.4 on 2021-06-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_expense_spender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='spender',
        ),
    ]
